### ISSUE TITLE
1.3.0 crashes with ae2

### ISSUE THREAD

**Issue by Chuunkyz** [paulevsGitch/BCLib#87] opened 2022-02-04 19:26 UTC
when entering a world with the minimal amount of mods, aka ae2 + bclib + cloth config + fabric api (latest versions !)

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 04/02/2022 20:24
Description: Exception in server tick loop

java.lang.ClassCastException: class appeng.spatial.SpatialStorageChunkGenerator cannot be cast to class ru.bclib.interfaces.NoiseGeneratorSettingsProvider (appeng.spatial.SpatialStorageChunkGenerator and ru.bclib.interfaces.NoiseGeneratorSettingsProvider are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @79351f41)
	at ru.bclib.api.biomes.BiomeAPI.lambda$applyModifications$14(BiomeAPI.java:505)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at ru.bclib.api.biomes.BiomeAPI.applyModifications(BiomeAPI.java:505)
	at net.minecraft.class_3218.handler$zco000$bclib_onServerWorldInit(class_3218.java:1663)
	at net.minecraft.class_3218.<init>(class_3218.java:247)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:412)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:327)
	at net.minecraft.class_1132.method_3823(class_1132.java:72)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1043368104 bytes (995 MiB) / 1979711488 bytes (1888 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2,30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x249d
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024,00
	Graphics card #1 deviceId: 0x9a60
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9415
	Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384,00
	Memory slot #1 clockSpeed (GHz): 3,20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37333,50
	Virtual memory used (MB): 16947,50
	Swap memory total (MB): 4864,00
	Swap memory used (MB): 86,81
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ae2: Applied Energistics 2 10.0.0
		bclib: BCLib 1.3.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.12.12
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.1
		team_reborn_energy: Energy 2.0.0-beta1
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by gniftygnome** [comment] 2022-02-04 20:45
Similarly, it crashes with Immersive Portals ... if you want this in a separate issue or a copy of the entire crash report, just let me know.

```
[12:27:41] [Server thread/INFO]: [bclib] Rebuilding features in BiomeSource class net.minecraft.class_4766
[12:27:42] [Server thread/INFO]: [bclib] Rebuilding features in BiomeSource class ru.bclib.world.generator.BCLibNetherBiomeSource
[12:27:42] [Server thread/INFO]: [bclib] Rebuilding features in BiomeSource class ru.bclib.world.generator.BCLibEndBiomeSource
[12:27:42] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: class qouteall.imm_ptl.peripheral.alternate_dimension.DelegatedChunkGenerator$SpecialNoise cannot be cast to class ru.bclib.interfaces.NoiseGeneratorSettingsProvider (qouteall.imm_ptl.peripheral.alternate_dimension.DelegatedChunkGenerator$SpecialNoise and ru.bclib.interfaces.NoiseGeneratorSettingsProvider are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @2d554825)
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.18) ~[?:?]
        at ru.bclib.api.biomes.BiomeAPI.lambda$applyModifications$14(BiomeAPI.java:505) ~[bclib-1.3.0.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at ru.bclib.api.biomes.BiomeAPI.applyModifications(BiomeAPI.java:505) ~[bclib-1.3.0.jar:?]
        at net.minecraft.server.world.ServerWorld.handler$zef000$bclib_onServerWorldInit(ServerWorld:3163) ~[?:?]
        at net.minecraft.server.world.ServerWorld.<init>(ServerWorld:247) ~[?:?]
        at net.minecraft.server.MinecraftServer.createWorlds(MinecraftServer:412) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer:327) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.MinecraftDedicatedServer.setupServer(MinecraftDedicatedServer:182) ~[?:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:657) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by HockeyZman2000** [comment] 2022-02-04 20:59
Can also reproduce this same issue. Took out Immersive Portals and then got the same crash as #86 with VoidZ

**Comment by paulevsGitch** [comment] 2022-02-05 00:47
Duplicate of https://github.com/paulevsGitch/BCLib/issues/85

**Closed by paulevsGitch** 2022-02-05 00:47 UTC
