### ISSUE TITLE
Crash when generating new world (BCLib1.3.0), workaround by rolling back to 1.2.5

### ISSUE THREAD

**Issue by rlane85** [paulevsGitch/BCLib#94] opened 2022-02-05 12:28 UTC
```
[07:05:34] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: class appeng.spatial.SpatialStorageChunkGenerator cannot be cast to class ru.bclib.interfaces.NoiseGeneratorSettingsProvider (appeng.spatial.SpatialStorageChunkGenerator and ru.bclib.interfaces.NoiseGeneratorSettingsProvider are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @135606db)
```

[latest.log](https://pastebin.com/raw/FeS6MW16)

**Comment by quiqueck** [comment] 2022-02-05 13:30
Duplicate of #85

**Closed by quiqueck** 2022-02-05 13:30 UTC
