### ISSUE TITLE
BCLIb incompatible with Paradise Lost mod

### ISSUE THREAD

**Issue by BitterestBoi** [paulevsGitch/BCLib#134] opened 2022-04-21 19:49 UTC
It shows that the bclib mod is unfortunately incomputable with Paradise Lost, as when I try to run both, they crash, however when I run them seperately they work fine. This is the crash log, to help support. 
![image_2022-04-21_205109224](https://user-images.githubusercontent.com/104167966/164541571-d2a9894b-1f01-4939-b916-8984779d67fa.png)

**Comment by paulevsGitch** [comment] 2022-04-21 21:56
Duplicate of #128, #130 and #133

**Closed by paulevsGitch** 2022-04-21 21:56 UTC
