### ISSUE TITLE
BCLIB incompatible with paradise reborn

### ISSUE THREAD

**Issue by Deceiverr13** [paulevsGitch/BCLib#130] opened 2022-04-14 03:21 UTC
I just discovered that bclib 1.4.3 is incompatible with paradise lost - the aether reborn 1.6.8 on 1.18.2. Would greatly appreciate if this could be fixed!!

**Comment by paulevsGitch** [comment] 2022-04-14 10:35
Technically this is a duplicate of #128

**Closed by paulevsGitch** 2022-04-14 10:35 UTC

**Comment by Deceiverr13** [comment] 2022-04-15 21:59
How is this a duplicate? It's a different mod.

**Comment by paulevsGitch** [comment] 2022-04-15 22:01
Paradise Reborn use embedded MoreTags inside, issue with MoreTags is already opened, so it is duplicate

**Comment by Deceiverr13** [comment] 2022-04-15 23:17
Ah, I see. Makes sense then. Thanks for clarifying!
