### ISSUE TITLE
Incompatibility with immersive portals, (now with the right crashlog)

### ISSUE THREAD

**Issue by Redd56** [paulevsGitch/BCLib#91] opened 2022-02-05 03:21 UTC
[here is the popper crashlog](https://pastebin.com/b75mkrAh)
bclib 1.3, immersive portals 1.2.5, fabric api 46.4

**Comment by paulevsGitch** [comment] 2022-02-05 03:40
Duplicate of https://github.com/paulevsGitch/BCLib/issues/85

**Closed by paulevsGitch** 2022-02-05 03:40 UTC
