### ISSUE TITLE
"bclib is incompatible with RecipeConfidence." Ive tried using the other 1.18.2 version and checked all my mods and they all were 1.18.2. Log link below

### ISSUE THREAD

**Issue by ZenCristinok** [paulevsGitch/BCLib#136] opened 2022-04-22 12:54 UTC
https://mclo.gs/mzthrGy

p.s Im not good at coding or reading code at all, all i know is how to put mods and config them so i have no idea.

**Comment by paulevsGitch** [comment] 2022-04-22 15:17
Duplicate of #128

**Closed by paulevsGitch** 2022-04-22 15:17 UTC
