### ISSUE TITLE
World crashes while generating if any other dimension mod presented

### ISSUE THREAD

**Issue by NordAct** [paulevsGitch/BCLib#86] opened 2022-02-04 19:21 UTC
[crash-2022-02-04_21.55.13-server.txt](https://github.com/paulevsGitch/BCLib/files/8005583/crash-2022-02-04_21.55.13-server.txt)
[crash-2022-02-04_21.58.12-server.txt](https://github.com/paulevsGitch/BCLib/files/8005582/crash-2022-02-04_21.58.12-server.txt)

According to first report case crash was caused by The Corners (adds new dimensions). Then on second run I turned it off and then same error happened to VoidZ (also adds new dimension)

**Comment by JDtheHutt** [comment] 2022-02-04 22:19
I am seeing the same with VoidZ since I updated BCLib to 1.3.0

**Comment by paulevsGitch** [comment] 2022-02-05 00:47
Duplicate of #85

**Closed by paulevsGitch** 2022-02-05 00:47 UTC
