### ISSUE TITLE
bclib is incompatible with RecipeConfidence.

### ISSUE THREAD

**Issue by greensad** [paulevsGitch/BCLib#104] opened 2022-02-19 22:43 UTC
When launching the game:

[16:45:30] [main/ERROR]: 
[16:45:30] [main/ERROR]: 
[16:45:30] [main/ERROR]: 
[16:45:30] [main/ERROR]: 
[16:45:30] [main/ERROR]: bclib is incompatible with RecipeConfidence.
[16:45:30] [main/ERROR]: 
[16:45:30] [main/ERROR]: There is a chance that the compatibility layer is not correct, issues may arise
[16:45:30] [main/ERROR]: when using recipes (crafting, smelting, etc.) because of the conflict.
[16:45:30] [main/ERROR]: 
[16:45:30] [main/ERROR]: If you are the authors of bclib and have validated the compatibility layer, feel
[16:45:30] [main/ERROR]: free to make a mixin that changes BclibFlag.bclibCompatValidated to return true.
[16:45:30] [main/ERROR]: 
[16:45:30] [main/ERROR]: 
[16:45:30] [main/ERROR]: 
[16:45:30] [main/ERROR]: 

**Log:** https://paste.ee/p/0ZBus

**Comment by paulevsGitch** [comment] 2022-02-20 05:08
Duplicate of #42

**Closed by paulevsGitch** 2022-02-20 05:08 UTC
